//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Apideck.Unify.SDK.Models.Components
{
    using Apideck.Unify.SDK.Models.Components;
    using Apideck.Unify.SDK.Utils;
    using Newtonsoft.Json;
    
    public class EmploymentRole
    {

        /// <summary>
        /// The type of employment relationship the employee has with the organization.
        /// </summary>
        [JsonProperty("type")]
        public EmploymentType? Type { get; set; } = null;

        /// <summary>
        /// The work schedule of the employee.
        /// </summary>
        [JsonProperty("sub_type")]
        public EmploymentSubType? SubType { get; set; } = null;
    }
}