//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Components
{
    using ApideckUnifySdk.Utils;
    using Newtonsoft.Json;

    /// <summary>
    /// The accounting period the expense report is posted to.
    /// </summary>
    public class AccountingPeriod
    {
        /// <summary>
        /// A unique identifier for the accounting period.
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// The name of the accounting period.
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; } = null;
    }
}