//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Components
{
    using ApideckUnifySdk.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Type of amortization.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class AmortizationType : IEquatable<AmortizationType>
    {
        public static readonly AmortizationType Manual = new AmortizationType("manual");
        public static readonly AmortizationType Receipt = new AmortizationType("receipt");
        public static readonly AmortizationType Schedule = new AmortizationType("schedule");
        public static readonly AmortizationType Other = new AmortizationType("other");

        private static readonly Dictionary <string, AmortizationType> _knownValues =
            new Dictionary <string, AmortizationType> ()
            {
                ["manual"] = Manual,
                ["receipt"] = Receipt,
                ["schedule"] = Schedule,
                ["other"] = Other
            };

        private static readonly ConcurrentDictionary<string, AmortizationType> _values =
            new ConcurrentDictionary<string, AmortizationType>(_knownValues);

        private AmortizationType(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static AmortizationType Of(string value)
        {
            return _values.GetOrAdd(value, _ => new AmortizationType(value));
        }

        public static implicit operator AmortizationType(string value) => Of(value);
        public static implicit operator string(AmortizationType amortizationtype) => amortizationtype.Value;

        public static AmortizationType[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as AmortizationType);

        public bool Equals(AmortizationType? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}