//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Components
{
    using ApideckUnifySdk.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The gender represents the gender identity of a person.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class ApplicantGender : IEquatable<ApplicantGender>
    {
        public static readonly ApplicantGender Male = new ApplicantGender("male");
        public static readonly ApplicantGender Female = new ApplicantGender("female");
        public static readonly ApplicantGender Unisex = new ApplicantGender("unisex");
        public static readonly ApplicantGender Other = new ApplicantGender("other");
        public static readonly ApplicantGender NotSpecified = new ApplicantGender("not_specified");

        private static readonly Dictionary <string, ApplicantGender> _knownValues =
            new Dictionary <string, ApplicantGender> ()
            {
                ["male"] = Male,
                ["female"] = Female,
                ["unisex"] = Unisex,
                ["other"] = Other,
                ["not_specified"] = NotSpecified
            };

        private static readonly ConcurrentDictionary<string, ApplicantGender> _values =
            new ConcurrentDictionary<string, ApplicantGender>(_knownValues);

        private ApplicantGender(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ApplicantGender Of(string value)
        {
            return _values.GetOrAdd(value, _ => new ApplicantGender(value));
        }

        public static implicit operator ApplicantGender(string value) => Of(value);
        public static implicit operator string(ApplicantGender applicantgender) => applicantgender.Value;

        public static ApplicantGender[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ApplicantGender);

        public bool Equals(ApplicantGender? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}