//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Components
{
    using ApideckUnifySdk.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Audience for the doc.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class Audience : IEquatable<Audience>
    {
        public static readonly Audience ApplicationOwner = new Audience("application_owner");
        public static readonly Audience Consumer = new Audience("consumer");

        private static readonly Dictionary <string, Audience> _knownValues =
            new Dictionary <string, Audience> ()
            {
                ["application_owner"] = ApplicationOwner,
                ["consumer"] = Consumer
            };

        private static readonly ConcurrentDictionary<string, Audience> _values =
            new ConcurrentDictionary<string, Audience>(_knownValues);

        private Audience(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static Audience Of(string value)
        {
            return _values.GetOrAdd(value, _ => new Audience(value));
        }

        public static implicit operator Audience(string value) => Of(value);
        public static implicit operator string(Audience audience) => audience.Value;

        public static Audience[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as Audience);

        public bool Equals(Audience? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}