//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Components
{
    using ApideckUnifySdk.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Type of the bank account.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class BankAccountType : IEquatable<BankAccountType>
    {
        public static readonly BankAccountType Bank = new BankAccountType("bank");
        public static readonly BankAccountType CreditCard = new BankAccountType("credit_card");

        private static readonly Dictionary <string, BankAccountType> _knownValues =
            new Dictionary <string, BankAccountType> ()
            {
                ["bank"] = Bank,
                ["credit_card"] = CreditCard
            };

        private static readonly ConcurrentDictionary<string, BankAccountType> _values =
            new ConcurrentDictionary<string, BankAccountType>(_knownValues);

        private BankAccountType(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static BankAccountType Of(string value)
        {
            return _values.GetOrAdd(value, _ => new BankAccountType(value));
        }

        public static implicit operator BankAccountType(string value) => Of(value);
        public static implicit operator string(BankAccountType bankaccounttype) => bankaccounttype.Value;

        public static BankAccountType[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as BankAccountType);

        public bool Equals(BankAccountType? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}