//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Components
{
    using ApideckUnifySdk.Models.Components;
    using ApideckUnifySdk.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    public class BatchItemResult
    {
        /// <summary>
        /// A caller-supplied reference for this item, echoed back on the matching result so each outcome can be tied to the record it came from. Must be unique within the request. Never sent to the connector.
        /// </summary>
        [JsonProperty("_ref")]
        public string? Ref { get; set; }

        /// <summary>
        /// A unique identifier for an object.
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// The third-party API ID of original entity.
        /// </summary>
        [JsonProperty("downstream_id")]
        public string? DownstreamId { get; set; } = null;

        /// <summary>
        /// The outcome for this item.<br/>
        /// <br/>
        /// - `created` / `updated` — the record was written.<br/>
        /// - `failed` — it was not written, and `error` says why.<br/>
        /// - `uncertain` — the request to the connector did not complete (typically a timeout), so whether this record was written is genuinely unknown. Do not blindly retry: list the resource to find what exists first, or a retry may duplicate it.<br/>
        /// <br/>
        /// A `created` or `updated` result can also carry an `error`: the record was written, but work that runs after the write did not complete.<br/>
        /// <br/>
        /// Read this rather than `id` to decide what happened. `id` is present when the identifier could also be read back, which is not the same question — a written record whose id could not be parsed still reports `created`.
        /// </summary>
        [JsonProperty("status")]
        public BatchItemResultStatus Status { get; set; } = default!;

        /// <summary>
        /// Why this item did not complete. Present when `status` is `failed`, meaning the record was not written, and when `status` is `uncertain`, meaning it is unknown whether it was. Also present, more rarely, alongside `created`/`updated`: the record WAS written and post-write processing failed, so the item reports the error beside its success status.<br/>
        /// <br/>
        /// Per-item failures are independent — one item's rejection says nothing about the others. The exception is a failure of the request itself, such as a timeout: where a connector writes the whole batch in one call, every item shares that outcome and carries the same error.
        /// </summary>
        [JsonProperty("error")]
        public Error? Error { get; set; }

        /// <summary>
        /// Non-fatal problems with THIS item — a currency the connector could not match, for example, which is sent without it. Present per item rather than per request, because a caller with twenty records needs to know which one was affected.<br/>
        /// <br/>
        /// A warning does not imply the record was written: some are raised while preparing the item, before the write is attempted, so they can appear on a `failed` item too. Read `status` for what happened.
        /// </summary>
        [JsonProperty("warnings")]
        public List<BatchItemResultWarnings>? Warnings { get; set; }
    }
}