//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Components
{
    using ApideckUnifySdk.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Status of bill credit notes.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class BillCreditNoteStatus : IEquatable<BillCreditNoteStatus>
    {
        public static readonly BillCreditNoteStatus Draft = new BillCreditNoteStatus("draft");
        public static readonly BillCreditNoteStatus Authorised = new BillCreditNoteStatus("authorised");
        public static readonly BillCreditNoteStatus Posted = new BillCreditNoteStatus("posted");
        public static readonly BillCreditNoteStatus PartiallyPaid = new BillCreditNoteStatus("partially_paid");
        public static readonly BillCreditNoteStatus Paid = new BillCreditNoteStatus("paid");
        public static readonly BillCreditNoteStatus Voided = new BillCreditNoteStatus("voided");
        public static readonly BillCreditNoteStatus Deleted = new BillCreditNoteStatus("deleted");

        private static readonly Dictionary <string, BillCreditNoteStatus> _knownValues =
            new Dictionary <string, BillCreditNoteStatus> ()
            {
                ["draft"] = Draft,
                ["authorised"] = Authorised,
                ["posted"] = Posted,
                ["partially_paid"] = PartiallyPaid,
                ["paid"] = Paid,
                ["voided"] = Voided,
                ["deleted"] = Deleted
            };

        private static readonly ConcurrentDictionary<string, BillCreditNoteStatus> _values =
            new ConcurrentDictionary<string, BillCreditNoteStatus>(_knownValues);

        private BillCreditNoteStatus(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static BillCreditNoteStatus Of(string value)
        {
            return _values.GetOrAdd(value, _ => new BillCreditNoteStatus(value));
        }

        public static implicit operator BillCreditNoteStatus(string value) => Of(value);
        public static implicit operator string(BillCreditNoteStatus billcreditnotestatus) => billcreditnotestatus.Value;

        public static BillCreditNoteStatus[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as BillCreditNoteStatus);

        public bool Equals(BillCreditNoteStatus? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}