//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Components
{
    using ApideckUnifySdk.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The type of credit note. A bill credit note is always an accounts payable (supplier-side) credit.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class BillCreditNoteType : IEquatable<BillCreditNoteType>
    {
        public static readonly BillCreditNoteType AccountsPayableCredit = new BillCreditNoteType("accounts_payable_credit");

        private static readonly Dictionary <string, BillCreditNoteType> _knownValues =
            new Dictionary <string, BillCreditNoteType> ()
            {
                ["accounts_payable_credit"] = AccountsPayableCredit
            };

        private static readonly ConcurrentDictionary<string, BillCreditNoteType> _values =
            new ConcurrentDictionary<string, BillCreditNoteType>(_knownValues);

        private BillCreditNoteType(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static BillCreditNoteType Of(string value)
        {
            return _values.GetOrAdd(value, _ => new BillCreditNoteType(value));
        }

        public static implicit operator BillCreditNoteType(string value) => Of(value);
        public static implicit operator string(BillCreditNoteType billcreditnotetype) => billcreditnotetype.Value;

        public static BillCreditNoteType[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as BillCreditNoteType);

        public bool Equals(BillCreditNoteType? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}