//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Components
{
    using ApideckUnifySdk.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Whether this credit note reduces an amount owed by a customer (accounts receivable) or owed to a supplier (accounts payable). `accounts_payable_credit` support is connector-specific — most connectors only expose the accounts-receivable side. Check the connector's gotchas for known deviations.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class CreditNoteCreateInputCreditNoteType : IEquatable<CreditNoteCreateInputCreditNoteType>
    {
        public static readonly CreditNoteCreateInputCreditNoteType AccountsReceivableCredit = new CreditNoteCreateInputCreditNoteType("accounts_receivable_credit");
        public static readonly CreditNoteCreateInputCreditNoteType AccountsPayableCredit = new CreditNoteCreateInputCreditNoteType("accounts_payable_credit");

        private static readonly Dictionary <string, CreditNoteCreateInputCreditNoteType> _knownValues =
            new Dictionary <string, CreditNoteCreateInputCreditNoteType> ()
            {
                ["accounts_receivable_credit"] = AccountsReceivableCredit,
                ["accounts_payable_credit"] = AccountsPayableCredit
            };

        private static readonly ConcurrentDictionary<string, CreditNoteCreateInputCreditNoteType> _values =
            new ConcurrentDictionary<string, CreditNoteCreateInputCreditNoteType>(_knownValues);

        private CreditNoteCreateInputCreditNoteType(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static CreditNoteCreateInputCreditNoteType Of(string value)
        {
            return _values.GetOrAdd(value, _ => new CreditNoteCreateInputCreditNoteType(value));
        }

        public static implicit operator CreditNoteCreateInputCreditNoteType(string value) => Of(value);
        public static implicit operator string(CreditNoteCreateInputCreditNoteType creditnotecreateinputcreditnotetype) => creditnotecreateinputcreditnotetype.Value;

        public static CreditNoteCreateInputCreditNoteType[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as CreditNoteCreateInputCreditNoteType);

        public bool Equals(CreditNoteCreateInputCreditNoteType? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}