//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Components
{
    using ApideckUnifySdk.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Status of customer to filter on.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class CustomersFilterStatus : IEquatable<CustomersFilterStatus>
    {
        public static readonly CustomersFilterStatus Active = new CustomersFilterStatus("active");
        public static readonly CustomersFilterStatus Inactive = new CustomersFilterStatus("inactive");
        public static readonly CustomersFilterStatus Archived = new CustomersFilterStatus("archived");
        public static readonly CustomersFilterStatus All = new CustomersFilterStatus("all");

        private static readonly Dictionary <string, CustomersFilterStatus> _knownValues =
            new Dictionary <string, CustomersFilterStatus> ()
            {
                ["active"] = Active,
                ["inactive"] = Inactive,
                ["archived"] = Archived,
                ["all"] = All
            };

        private static readonly ConcurrentDictionary<string, CustomersFilterStatus> _values =
            new ConcurrentDictionary<string, CustomersFilterStatus>(_knownValues);

        private CustomersFilterStatus(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static CustomersFilterStatus Of(string value)
        {
            return _values.GetOrAdd(value, _ => new CustomersFilterStatus(value));
        }

        public static implicit operator CustomersFilterStatus(string value) => Of(value);
        public static implicit operator string(CustomersFilterStatus customersfilterstatus) => customersfilterstatus.Value;

        public static CustomersFilterStatus[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as CustomersFilterStatus);

        public bool Equals(CustomersFilterStatus? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}