//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Components
{
    using ApideckUnifySdk.Models.Components;
    using ApideckUnifySdk.Utils;
    using Newtonsoft.Json;
    
    public class DataScopes
    {

        /// <summary>
        /// Whether Data Scopes is enabled for this application
        /// </summary>
        [JsonProperty("enabled")]
        public bool? Enabled { get; set; }

        /// <summary>
        /// ISO timestamp of when the Data Scopes configuration was last modified
        /// </summary>
        [JsonProperty("updated_at")]
        public string? UpdatedAt { get; set; }

        /// <summary>
        /// Data scopes resource configuration that can be either detailed field permissions or a wildcard
        /// </summary>
        [JsonProperty("resources", NullValueHandling = NullValueHandling.Include)]
        public DataScopesResources? Resources { get; set; }
    }
}