//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Components
{
    using ApideckUnifySdk.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Indicates the status of the job.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class EmployeeJobStatus : IEquatable<EmployeeJobStatus>
    {
        public static readonly EmployeeJobStatus Active = new EmployeeJobStatus("active");
        public static readonly EmployeeJobStatus Inactive = new EmployeeJobStatus("inactive");
        public static readonly EmployeeJobStatus Other = new EmployeeJobStatus("other");

        private static readonly Dictionary <string, EmployeeJobStatus> _knownValues =
            new Dictionary <string, EmployeeJobStatus> ()
            {
                ["active"] = Active,
                ["inactive"] = Inactive,
                ["other"] = Other
            };

        private static readonly ConcurrentDictionary<string, EmployeeJobStatus> _values =
            new ConcurrentDictionary<string, EmployeeJobStatus>(_knownValues);

        private EmployeeJobStatus(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static EmployeeJobStatus Of(string value)
        {
            return _values.GetOrAdd(value, _ => new EmployeeJobStatus(value));
        }

        public static implicit operator EmployeeJobStatus(string value) => Of(value);
        public static implicit operator string(EmployeeJobStatus employeejobstatus) => employeejobstatus.Value;

        public static EmployeeJobStatus[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as EmployeeJobStatus);

        public bool Equals(EmployeeJobStatus? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}