//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Components
{
    using ApideckUnifySdk.Models.Components;
    using ApideckUnifySdk.Utils;
    using Newtonsoft.Json;
    using NodaTime;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    public class ExpenseReportLineItemInput
    {
        /// <summary>
        /// Line number of the resource.
        /// </summary>
        [JsonProperty("line_number")]
        public long? LineNumber { get; set; } = null;

        /// <summary>
        /// The expense category this entity is linked to.
        /// </summary>
        [JsonProperty("expense_category")]
        public LinkedExpenseCategory? ExpenseCategory { get; set; }

        [JsonProperty("account")]
        public LinkedLedgerAccount? Account { get; set; } = null;

        /// <summary>
        /// The description of the expense line item.
        /// </summary>
        [JsonProperty("description")]
        public string? Description { get; set; } = null;

        [JsonProperty("quantity")]
        public double? Quantity { get; set; } = null;

        [JsonProperty("unit_price")]
        public double? UnitPrice { get; set; } = null;

        /// <summary>
        /// The amount of the expense line item.
        /// </summary>
        [JsonProperty("amount")]
        public double Amount { get; set; } = default!;

        [JsonProperty("tax_rate")]
        public LinkedTaxRateInput? TaxRate { get; set; }

        /// <summary>
        /// Tax amount.
        /// </summary>
        [JsonProperty("tax_amount")]
        public double? TaxAmount { get; set; } = null;

        /// <summary>
        /// The total amount of the expense line item including tax.
        /// </summary>
        [JsonProperty("total_amount")]
        public double? TotalAmount { get; set; } = null;

        /// <summary>
        /// The date of the individual expense.
        /// </summary>
        [JsonProperty("transaction_date")]
        public LocalDate? TransactionDate { get; set; } = null;

        /// <summary>
        /// Whether the expense is billable to a customer.
        /// </summary>
        [JsonProperty("billable")]
        public bool? Billable { get; set; } = null;

        /// <summary>
        /// Whether the expense is reimbursable to the employee.
        /// </summary>
        [JsonProperty("reimbursable")]
        public bool? Reimbursable { get; set; } = null;

        /// <summary>
        /// The customer this entity is linked to.
        /// </summary>
        [JsonProperty("customer")]
        public LinkedCustomerInput? Customer { get; set; } = null;

        [JsonProperty("department")]
        public LinkedDepartmentInput? Department { get; set; } = null;

        [JsonProperty("location")]
        public LinkedLocationInput? Location { get; set; } = null;

        /// <summary>
        /// A list of linked tracking categories.
        /// </summary>
        [JsonProperty("tracking_categories")]
        public List<LinkedTrackingCategory?>? TrackingCategories { get; set; } = null;

        /// <summary>
        /// URL to the receipt or attachment for this expense line.
        /// </summary>
        [JsonProperty("receipt_url")]
        public string? ReceiptUrl { get; set; } = null;

        /// <summary>
        /// Indicates the associated currency for an amount of money. Values correspond to <a href="https://en.wikipedia.org/wiki/ISO_4217">ISO 4217</a>.
        /// </summary>
        [JsonProperty("currency")]
        public Currency? Currency { get; set; } = null;
    }
}