//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Components
{
    using ApideckUnifySdk.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The type of resource. Could be file, folder or url.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class FileType : IEquatable<FileType>
    {
        public static readonly FileType File = new FileType("file");
        public static readonly FileType Folder = new FileType("folder");
        public static readonly FileType Url = new FileType("url");

        private static readonly Dictionary <string, FileType> _knownValues =
            new Dictionary <string, FileType> ()
            {
                ["file"] = File,
                ["folder"] = Folder,
                ["url"] = Url
            };

        private static readonly ConcurrentDictionary<string, FileType> _values =
            new ConcurrentDictionary<string, FileType>(_knownValues);

        private FileType(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static FileType Of(string value)
        {
            return _values.GetOrAdd(value, _ => new FileType(value));
        }

        public static implicit operator FileType(string value) => Of(value);
        public static implicit operator string(FileType filetype) => filetype.Value;

        public static FileType[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as FileType);

        public bool Equals(FileType? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}