//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Components
{
    using ApideckUnifySdk.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Side of the entry. Redundant with the sign of net_amount but exposed as an explicit flag for filtering convenience.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class GeneralLedgerTransactionLineItemType : IEquatable<GeneralLedgerTransactionLineItemType>
    {
        public static readonly GeneralLedgerTransactionLineItemType Debit = new GeneralLedgerTransactionLineItemType("debit");
        public static readonly GeneralLedgerTransactionLineItemType Credit = new GeneralLedgerTransactionLineItemType("credit");

        private static readonly Dictionary <string, GeneralLedgerTransactionLineItemType> _knownValues =
            new Dictionary <string, GeneralLedgerTransactionLineItemType> ()
            {
                ["debit"] = Debit,
                ["credit"] = Credit
            };

        private static readonly ConcurrentDictionary<string, GeneralLedgerTransactionLineItemType> _values =
            new ConcurrentDictionary<string, GeneralLedgerTransactionLineItemType>(_knownValues);

        private GeneralLedgerTransactionLineItemType(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static GeneralLedgerTransactionLineItemType Of(string value)
        {
            return _values.GetOrAdd(value, _ => new GeneralLedgerTransactionLineItemType(value));
        }

        public static implicit operator GeneralLedgerTransactionLineItemType(string value) => Of(value);
        public static implicit operator string(GeneralLedgerTransactionLineItemType generalledgertransactionlineitemtype) => generalledgertransactionlineitemtype.Value;

        public static GeneralLedgerTransactionLineItemType[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as GeneralLedgerTransactionLineItemType);

        public bool Equals(GeneralLedgerTransactionLineItemType? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}