//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Components
{
    using ApideckUnifySdk.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The kind of transaction, indicating whether it is a sales transaction or a purchase transaction.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class InvoiceItemFilterTransactionType : IEquatable<InvoiceItemFilterTransactionType>
    {
        public static readonly InvoiceItemFilterTransactionType Sale = new InvoiceItemFilterTransactionType("sale");
        public static readonly InvoiceItemFilterTransactionType Purchase = new InvoiceItemFilterTransactionType("purchase");

        private static readonly Dictionary <string, InvoiceItemFilterTransactionType> _knownValues =
            new Dictionary <string, InvoiceItemFilterTransactionType> ()
            {
                ["sale"] = Sale,
                ["purchase"] = Purchase
            };

        private static readonly ConcurrentDictionary<string, InvoiceItemFilterTransactionType> _values =
            new ConcurrentDictionary<string, InvoiceItemFilterTransactionType>(_knownValues);

        private InvoiceItemFilterTransactionType(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static InvoiceItemFilterTransactionType Of(string value)
        {
            return _values.GetOrAdd(value, _ => new InvoiceItemFilterTransactionType(value));
        }

        public static implicit operator InvoiceItemFilterTransactionType(string value) => Of(value);
        public static implicit operator string(InvoiceItemFilterTransactionType invoiceitemfiltertransactiontype) => invoiceitemfiltertransactiontype.Value;

        public static InvoiceItemFilterTransactionType[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as InvoiceItemFilterTransactionType);

        public bool Equals(InvoiceItemFilterTransactionType? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}