//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Components
{
    using ApideckUnifySdk.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    [JsonConverter(typeof(OpenEnumConverter))]
    public class JobType : IEquatable<JobType>
    {
        public static readonly JobType JobPortal = new JobType("job_portal");
        public static readonly JobType JobDescription = new JobType("job_description");

        private static readonly Dictionary <string, JobType> _knownValues =
            new Dictionary <string, JobType> ()
            {
                ["job_portal"] = JobPortal,
                ["job_description"] = JobDescription
            };

        private static readonly ConcurrentDictionary<string, JobType> _values =
            new ConcurrentDictionary<string, JobType>(_knownValues);

        private JobType(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static JobType Of(string value)
        {
            return _values.GetOrAdd(value, _ => new JobType(value));
        }

        public static implicit operator JobType(string value) => Of(value);
        public static implicit operator string(JobType jobtype) => jobtype.Value;

        public static JobType[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as JobType);

        public bool Equals(JobType? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}