//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Components
{
    using ApideckUnifySdk.Utils;
    using Newtonsoft.Json;
    using System;
    
    /// <summary>
    /// The type of account being referenced. Use `ledger_account` for GL accounts from the chart of accounts, or `bank_account` for bank account entities. When not specified, the connector will use its default behavior.
    /// </summary>
    public enum LinkedFinancialAccountAccountType
    {
        [JsonProperty("ledger_account")]
        LedgerAccount,
        [JsonProperty("bank_account")]
        BankAccount,
    }

    public static class LinkedFinancialAccountAccountTypeExtension
    {
        public static string Value(this LinkedFinancialAccountAccountType value)
        {
            return ((JsonPropertyAttribute)value.GetType().GetMember(value.ToString())[0].GetCustomAttributes(typeof(JsonPropertyAttribute), false)[0]).PropertyName ?? value.ToString();
        }

        public static LinkedFinancialAccountAccountType ToEnum(this string value)
        {
            foreach(var field in typeof(LinkedFinancialAccountAccountType).GetFields())
            {
                var attributes = field.GetCustomAttributes(typeof(JsonPropertyAttribute), false);
                if (attributes.Length == 0)
                {
                    continue;
                }

                var attribute = attributes[0] as JsonPropertyAttribute;
                if (attribute != null && attribute.PropertyName == value)
                {
                    var enumVal = field.GetValue(null);

                    if (enumVal is LinkedFinancialAccountAccountType)
                    {
                        return (LinkedFinancialAccountAccountType)enumVal;
                    }
                }
            }

            throw new Exception($"Unknown value {value} for enum LinkedFinancialAccountAccountType");
        }
    }

}