//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Components
{
    using ApideckUnifySdk.Models.Components;
    using ApideckUnifySdk.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    public class List
    {
        /// <summary>
        /// The unique identifier of the List.
        /// </summary>
        [JsonProperty("id")]
        public string Id { get; set; } = default!;

        /// <summary>
        /// The name of the List.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; } = default!;

        /// <summary>
        /// The description of the List.
        /// </summary>
        [JsonProperty("description")]
        public string? Description { get; set; } = null;

        /// <summary>
        /// Whether the List is static (a fixed set of records) or dynamic (a saved segment that is automatically kept up to date based on filter criteria).
        /// </summary>
        [JsonProperty("type")]
        public ListType? Type { get; set; } = null;

        /// <summary>
        /// The visibility of the List. Which of these values a given connector can return depends on its native sharing model — see the connector-specific gotchas below for details.
        /// </summary>
        [JsonProperty("visibility")]
        public ListVisibility? Visibility { get; set; } = null;

        /// <summary>
        /// The unique identifier of the user who owns the List.
        /// </summary>
        [JsonProperty("owner_id")]
        public string? OwnerId { get; set; } = null;

        /// <summary>
        /// The filter criteria used to determine which records belong to a dynamic List. Shape is connector-native and passed through largely as-is (e.g. Close returns its own nested query-tree structure) rather than normalized to a common format.
        /// </summary>
        [JsonProperty("filter_criteria")]
        public Dictionary<string, object>? FilterCriteria { get; set; } = null;

        /// <summary>
        /// The number of records currently in the List.
        /// </summary>
        [JsonProperty("record_count")]
        public long? RecordCount { get; set; } = null;

        /// <summary>
        /// The unique identifier of the folder the List is organized under.
        /// </summary>
        [JsonProperty("folder_id")]
        public string? FolderId { get; set; } = null;

        /// <summary>
        /// The type of CRM records the List contains. Normalized to a lowercase plural noun for the vendor's standard object types (e.g. contacts, companies, opportunities, leads, tickets, campaigns, tasks, events); for vendor-specific or custom object types the raw downstream identifier is passed through unchanged, following the connector's native casing (e.g. a HubSpot custom objectTypeId like 2-12345 or a Salesforce custom object API name), so a raw value may not always be distinguishable from a normalized one. This field is intentionally open-ended — no closed enum is enforced.
        /// </summary>
        [JsonProperty("object_type")]
        public string? ObjectType { get; set; } = null;

        /// <summary>
        /// Whether the List is dynamic, meaning its records are automatically kept up to date based on filter criteria. This is a boolean mirror of `type` (`true` when `type` is `dynamic`, `false` when `static`), provided for callers that prefer a boolean check over a string comparison.
        /// </summary>
        [JsonProperty("is_dynamic")]
        public bool? IsDynamic { get; set; } = null;

        /// <summary>
        /// Whether the List has been marked as a favorite.
        /// </summary>
        [JsonProperty("is_favorite")]
        public bool? IsFavorite { get; set; } = null;

        /// <summary>
        /// Whether the List is a default List.
        /// </summary>
        [JsonProperty("is_default")]
        public bool? IsDefault { get; set; } = null;

        /// <summary>
        /// Whether the List is a system-generated List.
        /// </summary>
        [JsonProperty("is_system")]
        public bool? IsSystem { get; set; } = null;

        [JsonProperty("custom_fields")]
        public List<CustomField>? CustomFields { get; set; }

        [JsonProperty("tags")]
        public List<string>? Tags { get; set; } = null;

        /// <summary>
        /// The unique identifier of the user who last updated the List.
        /// </summary>
        [JsonProperty("updated_by")]
        public string? UpdatedBy { get; set; } = null;

        /// <summary>
        /// The unique identifier of the user who created the List.
        /// </summary>
        [JsonProperty("created_by")]
        public string? CreatedBy { get; set; } = null;

        /// <summary>
        /// The date and time when the List was last updated.
        /// </summary>
        [JsonProperty("updated_at")]
        public DateTime? UpdatedAt { get; set; } = null;

        /// <summary>
        /// The date and time when the List was created.
        /// </summary>
        [JsonProperty("created_at")]
        public DateTime? CreatedAt { get; set; } = null;
    }
}