//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Components
{
    using ApideckUnifySdk.Models.Components;
    using ApideckUnifySdk.Utils;
    using Newtonsoft.Json;
    using NodaTime;
    using System;
    using System.Collections.Generic;
    
    public class Opportunity
    {

        /// <summary>
        /// A unique identifier for the opportunity.
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// The title or name of the opportunity.
        /// </summary>
        [JsonProperty("title")]
        public string Title { get; set; } = default!;

        /// <summary>
        /// The unique identifier of the primary contact associated with the opportunity.
        /// </summary>
        [JsonProperty("primary_contact_id")]
        public string? PrimaryContactId { get; set; } = null;

        /// <summary>
        /// A description of the opportunity.
        /// </summary>
        [JsonProperty("description")]
        public string? Description { get; set; } = null;

        /// <summary>
        /// The type of the opportunity
        /// </summary>
        [JsonProperty("type")]
        public string? Type { get; set; } = null;

        /// <summary>
        /// The monetary value associated with the opportunity
        /// </summary>
        [JsonProperty("monetary_amount")]
        public double? MonetaryAmount { get; set; } = null;

        /// <summary>
        /// Indicates the associated currency for an amount of money. Values correspond to <a href="https://en.wikipedia.org/wiki/ISO_4217">ISO 4217</a>.
        /// </summary>
        [JsonProperty("currency")]
        public Currency? Currency { get; set; } = null;

        /// <summary>
        /// The probability of winning the opportunity, expressed as a percentage.
        /// </summary>
        [JsonProperty("win_probability")]
        public double? WinProbability { get; set; } = null;

        /// <summary>
        /// The expected revenue from the opportunity
        /// </summary>
        [JsonProperty("expected_revenue")]
        public double? ExpectedRevenue { get; set; } = null;

        /// <summary>
        /// The actual closing date for the opportunity. If close_date is null, the opportunity is not closed yet.
        /// </summary>
        [JsonProperty("close_date")]
        public LocalDate? CloseDate { get; set; } = null;

        /// <summary>
        /// The unique identifier of the reason why the opportunity was lost.
        /// </summary>
        [JsonProperty("loss_reason_id")]
        public string? LossReasonId { get; set; } = null;

        /// <summary>
        /// The reason why the opportunity was lost.
        /// </summary>
        [JsonProperty("loss_reason")]
        public string? LossReason { get; set; } = null;

        /// <summary>
        /// The unique identifier of the reason why the opportunity was won.
        /// </summary>
        [JsonProperty("won_reason_id")]
        public string? WonReasonId { get; set; } = null;

        /// <summary>
        /// The reason why the opportunity was won.
        /// </summary>
        [JsonProperty("won_reason")]
        public string? WonReason { get; set; } = null;

        /// <summary>
        /// The unique identifier of the pipeline associated with the opportunity
        /// </summary>
        [JsonProperty("pipeline_id")]
        public string? PipelineId { get; set; } = null;

        /// <summary>
        /// The unique identifier of the stage in the pipeline associated with the opportunity.
        /// </summary>
        [JsonProperty("pipeline_stage_id")]
        public string? PipelineStageId { get; set; } = null;

        /// <summary>
        /// The unique identifier of the source of the opportunity.
        /// </summary>
        [JsonProperty("source_id")]
        public string? SourceId { get; set; } = null;

        /// <summary>
        /// The unique identifier of the lead associated with the opportunity.
        /// </summary>
        [JsonProperty("lead_id")]
        public string? LeadId { get; set; } = null;

        /// <summary>
        /// The source of the lead associated with the opportunity.
        /// </summary>
        [JsonProperty("lead_source")]
        public string? LeadSource { get; set; } = null;

        /// <summary>
        /// The unique identifier of the contact associated with the opportunity.
        /// </summary>
        [JsonProperty("contact_id")]
        public string? ContactId { get; set; } = null;

        /// <summary>
        /// An array of unique identifiers of all contacts associated with the opportunity.
        /// </summary>
        [JsonProperty("contact_ids")]
        public List<string>? ContactIds { get; set; }

        /// <summary>
        /// The unique identifier of the company associated with the opportunity.
        /// </summary>
        [JsonProperty("company_id")]
        public string? CompanyId { get; set; } = null;

        /// <summary>
        /// The name of the company associated with the opportunity.
        /// </summary>
        [JsonProperty("company_name")]
        public string? CompanyName { get; set; } = null;

        /// <summary>
        /// The unique identifier of the user who owns the opportunity.
        /// </summary>
        [JsonProperty("owner_id")]
        public string? OwnerId { get; set; } = null;

        /// <summary>
        /// The priority level of the opportunity.
        /// </summary>
        [JsonProperty("priority")]
        public string? Priority { get; set; } = null;

        /// <summary>
        /// The current status of the opportunity.
        /// </summary>
        [JsonProperty("status")]
        public string? Status { get; set; } = null;

        /// <summary>
        /// The unique identifier of the current status of the opportunity.
        /// </summary>
        [JsonProperty("status_id")]
        public string? StatusId { get; set; } = null;

        [JsonProperty("tags")]
        public List<string>? Tags { get; set; } = null;

        /// <summary>
        /// The number of interactions with the opportunity.
        /// </summary>
        [JsonProperty("interaction_count")]
        public double? InteractionCount { get; set; } = null;

        [JsonProperty("custom_fields")]
        public List<CustomField>? CustomFields { get; set; }

        /// <summary>
        /// The date and time when the stage of the opportunity was last changed.
        /// </summary>
        [JsonProperty("stage_last_changed_at")]
        public DateTime? StageLastChangedAt { get; set; } = null;

        /// <summary>
        /// The date and time of the last activity associated with the opportunity.
        /// </summary>
        [JsonProperty("last_activity_at")]
        public string? LastActivityAt { get; set; } = null;

        /// <summary>
        /// Indicates whether the opportunity has been deleted.
        /// </summary>
        [JsonProperty("deleted")]
        public bool? Deleted { get; set; }

        /// <summary>
        /// The date and time when the stage of the opportunity was last changed.
        /// </summary>
        [JsonProperty("date_stage_changed")]
        public DateTime? DateStageChanged { get; set; } = null;

        /// <summary>
        /// The date and time when the opportunity was last contacted.
        /// </summary>
        [JsonProperty("date_last_contacted")]
        public DateTime? DateLastContacted { get; set; } = null;

        /// <summary>
        /// The date and time when the lead associated with the opportunity was created.
        /// </summary>
        [JsonProperty("date_lead_created")]
        public DateTime? DateLeadCreated { get; set; } = null;

        /// <summary>
        /// When custom mappings are configured on the resource, the result is included here.
        /// </summary>
        [JsonProperty("custom_mappings")]
        public Dictionary<string, object>? CustomMappings { get; set; } = null;

        /// <summary>
        /// The unique identifier of the user who last updated the opportunity.
        /// </summary>
        [JsonProperty("updated_by")]
        public string? UpdatedBy { get; set; } = null;

        /// <summary>
        /// The unique identifier of the user who created the opportunity.
        /// </summary>
        [JsonProperty("created_by")]
        public string? CreatedBy { get; set; } = null;

        /// <summary>
        /// The date and time when the opportunity was last updated.
        /// </summary>
        [JsonProperty("updated_at")]
        public DateTime? UpdatedAt { get; set; } = null;

        /// <summary>
        /// The date and time when the opportunity was created.
        /// </summary>
        [JsonProperty("created_at")]
        public DateTime? CreatedAt { get; set; } = null;

        /// <summary>
        /// The pass_through property allows passing service-specific, custom data or structured modifications in request body when creating or updating resources.
        /// </summary>
        [JsonProperty("pass_through")]
        public List<PassThroughBody>? PassThrough { get; set; }
    }
}