//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Components
{
    using ApideckUnifySdk.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The current status of the product (active or archived).
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class ProductStatus : IEquatable<ProductStatus>
    {
        public static readonly ProductStatus Active = new ProductStatus("active");
        public static readonly ProductStatus Archived = new ProductStatus("archived");

        private static readonly Dictionary <string, ProductStatus> _knownValues =
            new Dictionary <string, ProductStatus> ()
            {
                ["active"] = Active,
                ["archived"] = Archived
            };

        private static readonly ConcurrentDictionary<string, ProductStatus> _values =
            new ConcurrentDictionary<string, ProductStatus>(_knownValues);

        private ProductStatus(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ProductStatus Of(string value)
        {
            return _values.GetOrAdd(value, _ => new ProductStatus(value));
        }

        public static implicit operator ProductStatus(string value) => Of(value);
        public static implicit operator string(ProductStatus productstatus) => productstatus.Value;

        public static ProductStatus[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ProductStatus);

        public bool Equals(ProductStatus? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}