//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Components
{
    using ApideckUnifySdk.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Status of projects to filter by.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class ProjectStatus : IEquatable<ProjectStatus>
    {
        public static readonly ProjectStatus Active = new ProjectStatus("active");
        public static readonly ProjectStatus Completed = new ProjectStatus("completed");
        public static readonly ProjectStatus OnHold = new ProjectStatus("on_hold");
        public static readonly ProjectStatus Cancelled = new ProjectStatus("cancelled");
        public static readonly ProjectStatus Draft = new ProjectStatus("draft");
        public static readonly ProjectStatus InProgress = new ProjectStatus("in_progress");
        public static readonly ProjectStatus Approved = new ProjectStatus("approved");
        public static readonly ProjectStatus Other = new ProjectStatus("other");

        private static readonly Dictionary <string, ProjectStatus> _knownValues =
            new Dictionary <string, ProjectStatus> ()
            {
                ["active"] = Active,
                ["completed"] = Completed,
                ["on_hold"] = OnHold,
                ["cancelled"] = Cancelled,
                ["draft"] = Draft,
                ["in_progress"] = InProgress,
                ["approved"] = Approved,
                ["other"] = Other
            };

        private static readonly ConcurrentDictionary<string, ProjectStatus> _values =
            new ConcurrentDictionary<string, ProjectStatus>(_knownValues);

        private ProjectStatus(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static ProjectStatus Of(string value)
        {
            return _values.GetOrAdd(value, _ => new ProjectStatus(value));
        }

        public static implicit operator ProjectStatus(string value) => Of(value);
        public static implicit operator string(ProjectStatus projectstatus) => projectstatus.Value;

        public static ProjectStatus[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as ProjectStatus);

        public bool Equals(ProjectStatus? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}