//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Components
{
    using ApideckUnifySdk.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Received events are scoped to connection or across integration.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class SubscriptionLevel : IEquatable<SubscriptionLevel>
    {
        public static readonly SubscriptionLevel Connection = new SubscriptionLevel("connection");
        public static readonly SubscriptionLevel Integration = new SubscriptionLevel("integration");

        private static readonly Dictionary <string, SubscriptionLevel> _knownValues =
            new Dictionary <string, SubscriptionLevel> ()
            {
                ["connection"] = Connection,
                ["integration"] = Integration
            };

        private static readonly ConcurrentDictionary<string, SubscriptionLevel> _values =
            new ConcurrentDictionary<string, SubscriptionLevel>(_knownValues);

        private SubscriptionLevel(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static SubscriptionLevel Of(string value)
        {
            return _values.GetOrAdd(value, _ => new SubscriptionLevel(value));
        }

        public static implicit operator SubscriptionLevel(string value) => Of(value);
        public static implicit operator string(SubscriptionLevel subscriptionlevel) => subscriptionlevel.Value;

        public static SubscriptionLevel[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as SubscriptionLevel);

        public bool Equals(SubscriptionLevel? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}