//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Components
{
    using ApideckUnifySdk.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// Tax rate status.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class TaxRateStatus : IEquatable<TaxRateStatus>
    {
        public static readonly TaxRateStatus Active = new TaxRateStatus("active");
        public static readonly TaxRateStatus Inactive = new TaxRateStatus("inactive");
        public static readonly TaxRateStatus Archived = new TaxRateStatus("archived");

        private static readonly Dictionary <string, TaxRateStatus> _knownValues =
            new Dictionary <string, TaxRateStatus> ()
            {
                ["active"] = Active,
                ["inactive"] = Inactive,
                ["archived"] = Archived
            };

        private static readonly ConcurrentDictionary<string, TaxRateStatus> _values =
            new ConcurrentDictionary<string, TaxRateStatus>(_knownValues);

        private TaxRateStatus(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static TaxRateStatus Of(string value)
        {
            return _values.GetOrAdd(value, _ => new TaxRateStatus(value));
        }

        public static implicit operator TaxRateStatus(string value) => Of(value);
        public static implicit operator string(TaxRateStatus taxratestatus) => taxratestatus.Value;

        public static TaxRateStatus[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as TaxRateStatus);

        public bool Equals(TaxRateStatus? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}