//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Components
{
    using ApideckUnifySdk.Utils;
    using Newtonsoft.Json;
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;

    /// <summary>
    /// The type of address.
    /// </summary>
    [JsonConverter(typeof(OpenEnumConverter))]
    public class Type : IEquatable<Type>
    {
        public static readonly Type Primary = new Type("primary");
        public static readonly Type Secondary = new Type("secondary");
        public static readonly Type Home = new Type("home");
        public static readonly Type Office = new Type("office");
        public static readonly Type Shipping = new Type("shipping");
        public static readonly Type Billing = new Type("billing");
        public static readonly Type Work = new Type("work");
        public static readonly Type Other = new Type("other");

        private static readonly Dictionary <string, Type> _knownValues =
            new Dictionary <string, Type> ()
            {
                ["primary"] = Primary,
                ["secondary"] = Secondary,
                ["home"] = Home,
                ["office"] = Office,
                ["shipping"] = Shipping,
                ["billing"] = Billing,
                ["work"] = Work,
                ["other"] = Other
            };

        private static readonly ConcurrentDictionary<string, Type> _values =
            new ConcurrentDictionary<string, Type>(_knownValues);

        private Type(string value)
        {
            if (value == null) throw new ArgumentNullException(nameof(value));
            Value = value;
        }

        public string Value { get; }

        public static Type Of(string value)
        {
            return _values.GetOrAdd(value, _ => new Type(value));
        }

        public static implicit operator Type(string value) => Of(value);
        public static implicit operator string(Type type) => type.Value;

        public static Type[] Values()
        {
            return _values.Values.ToArray();
        }

        public override string ToString() => Value.ToString();

        public bool IsKnown()
        {
            return _knownValues.ContainsKey(Value);
        }

        public override bool Equals(object? obj) => Equals(obj as Type);

        public bool Equals(Type? other)
        {
            if (ReferenceEquals(this, other)) return true;
            if (other is null) return false;
            return string.Equals(Value, other.Value);
        }

        public override int GetHashCode() => Value.GetHashCode();
    }
}