//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Unify.Models.Components
{
    using Newtonsoft.Json;
    using System.Collections.Generic;
    using Unify.Models.Components;
    using Unify.Utils;
    
    public class Defaults
    {

        [JsonProperty("target")]
        public Target? Target { get; set; }

        [JsonProperty("id")]
        public string? Id { get; set; }

        [JsonProperty("options")]
        public List<FormFieldOption>? Options { get; set; }

        [JsonProperty("value")]
        public ConnectionValue? Value { get; set; }
    }
}