//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace Unify.Models.Components
{
    using Newtonsoft.Json;
    using Unify.Utils;
    
    public class Tax
    {

        /// <summary>
        /// The name of the tax.
        /// </summary>
        [JsonProperty("name")]
        public string? Name { get; set; } = null;

        /// <summary>
        /// Paid by employer.
        /// </summary>
        [JsonProperty("employer")]
        public bool? Employer { get; set; } = null;

        /// <summary>
        /// The amount of the tax.
        /// </summary>
        [JsonProperty("amount")]
        public double? Amount { get; set; } = null;
    }
}