//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApiDeckSdk.Models.Components
{
    using ApiDeckSdk.Models.Components;
    using ApiDeckSdk.Utils;
    using Newtonsoft.Json;
    using System.Collections.Generic;
    
    /// <summary>
    /// Unify event that is supported on the connector. Events are delivered via Webhooks.
    /// </summary>
    public class ConnectorEvent
    {

        /// <summary>
        /// Unify event type
        /// </summary>
        [JsonProperty("event_type")]
        public string? EventType { get; set; }

        /// <summary>
        /// Unify event source
        /// </summary>
        [JsonProperty("event_source")]
        public EventSource? EventSource { get; set; }

        /// <summary>
        /// Downstream event type
        /// </summary>
        [JsonProperty("downstream_event_type")]
        public string? DownstreamEventType { get; set; }

        [JsonProperty("resources")]
        public List<string>? Resources { get; set; }

        /// <summary>
        /// Unify entity type
        /// </summary>
        [JsonProperty("entity_type")]
        public string? EntityType { get; set; }
    }
}