//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApiDeckSdk.Models.Components
{
    using ApiDeckSdk.Utils;
    using Newtonsoft.Json;
    
    public class LinkedLedgerAccountInput
    {

        /// <summary>
        /// The unique identifier for the account.
        /// </summary>
        [JsonProperty("id")]
        public string? Id { get; set; }

        /// <summary>
        /// The nominal code of the account.
        /// </summary>
        [JsonProperty("nominal_code")]
        public string? NominalCode { get; set; } = null;

        /// <summary>
        /// The code assigned to the account.
        /// </summary>
        [JsonProperty("code")]
        public string? Code { get; set; } = null;
    }
}