//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk
{
    using ApideckUnifySdk.Models.Components;
    using ApideckUnifySdk.Models.Errors;
    using ApideckUnifySdk.Utils;
    using System;

    public interface IAts
    {
        public IJobs Jobs { get; }

        public IApplicants Applicants { get; }

        public IApplications Applications { get; }
    }

    public class Ats: IAts
    {
        /// <summary>
        /// SDK Configuration.
        /// <see cref="SDKConfig"/>
        /// </summary>
        public SDKConfig SDKConfiguration { get; private set; }

        /// <summary>
        /// Jobs SubSDK.
        /// <see cref="IJobs"/>
        /// </summary>
        public IJobs Jobs { get; private set; }

        /// <summary>
        /// Applicants SubSDK.
        /// <see cref="IApplicants"/>
        /// </summary>
        public IApplicants Applicants { get; private set; }

        /// <summary>
        /// Applications SubSDK.
        /// <see cref="IApplications"/>
        /// </summary>
        public IApplications Applications { get; private set; }

        public Ats(SDKConfig config)
        {
            SDKConfiguration = config;
            Jobs = new Jobs(SDKConfiguration);
            Applicants = new Applicants(SDKConfiguration);
            Applications = new Applications(SDKConfiguration);
        }
    }
}