//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Errors
{
    using ApideckUnifySdk.Utils;
    using Newtonsoft.Json;

    public class DownstreamErrors
    {
        /// <summary>
        /// Error message from the downstream provider.
        /// </summary>
        [JsonProperty("message")]
        public string? Message { get; set; }

        /// <summary>
        /// Additional error details.
        /// </summary>
        [JsonProperty("detail")]
        public string? Detail { get; set; }

        /// <summary>
        /// Error code from the downstream provider.
        /// </summary>
        [JsonProperty("code")]
        public string? Code { get; set; }
    }
}