//------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
namespace ApideckUnifySdk.Models.Requests
{
    using ApideckUnifySdk.Utils;

    public class ProxyPatchProxyRequest
    {
        /// <summary>
        /// ID of the consumer which you want to get or push data from.
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=x-apideck-consumer-id")]
        public string? ConsumerId { get; set; }

        /// <summary>
        /// The ID of your Unify application.
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=x-apideck-app-id")]
        public string? AppId { get; set; }

        /// <summary>
        /// Provide the service id you want to call (e.g., pipedrive). Only needed when a consumer has activated multiple integrations for a Unified API.
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=x-apideck-service-id")]
        public string ServiceId { get; set; } = default!;

        /// <summary>
        /// Specify which unified API to use for the connection lookup. Required for multi-API connectors (e.g., Workday) to ensure the correct credentials are used.
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=x-apideck-unified-api")]
        public string? UnifiedApi { get; set; }

        /// <summary>
        /// Downstream URL.
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=x-apideck-downstream-url")]
        public string DownstreamUrl { get; set; } = default!;

        /// <summary>
        /// Downstream authorization header. This will skip the Vault token injection.
        /// </summary>
        [SpeakeasyMetadata("header:style=simple,explode=false,name=x-apideck-downstream-authorization")]
        public string? DownstreamAuthorization { get; set; }

        /// <summary>
        /// Depending on the verb/method of the request this will contain the request body you want to POST/PATCH/PUT.
        /// </summary>
        [SpeakeasyMetadata("request:mediaType=*/*")]
        public byte[]? RequestBody { get; set; }
    }
}